name: Mirror dev to beta

on:
  push:
    branches: [dev]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout

      - name: Merge dev -> beta
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: beta
          github_token: ${{ secrets.GH_TOKEN }}
